openapi: 3.0.3
info:
  title: IoT Plant Watering Server API
  description: Backend server API for managing plant watering systems, user authentication, plant configurations, and historical data
  version: 1.0.0
  contact:
    name: Plant Watering System

servers:
  - url: https://api.plant-watering.example.com/api/v1
    description: Production server
  - url: http://localhost:3000/api/v1
    description: Development server

tags:
  - name: authentication
    description: User authentication operations
  - name: users
    description: User management
  - name: plants
    description: Plant management and configuration
  - name: measurements
    description: Historical sensor measurements
  - name: watering
    description: Watering control and history
  - name: controllers
    description: Controller device management

# Import security schemes
security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      tags:
        - authentication
      summary: Create a new user account
      description: Register a new user in the system
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/auth.yaml#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    format: uuid
                  email:
                    type: string
                  username:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        '400':
          $ref: './common/responses.yaml#/components/responses/BadRequest'
        '409':
          $ref: './common/responses.yaml#/components/responses/Conflict'

  /auth/login:
    post:
      tags:
        - authentication
      summary: User login
      description: Authenticate a user and return access token
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/auth.yaml#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: './server/schemas/auth.yaml#/components/schemas/AuthResponse'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

  /auth/logout:
    post:
      tags:
        - authentication
      summary: User logout
      description: Invalidate user session
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Logged out successfully"
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

  /auth/refresh:
    post:
      tags:
        - authentication
      summary: Refresh access token
      description: Get a new access token using refresh token
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/auth.yaml#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: './server/schemas/auth.yaml#/components/schemas/TokenResponse'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

  /users/me:
    get:
      tags:
        - users
      summary: Get current user profile
      description: Returns the profile of the authenticated user
      operationId: getCurrentUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: './server/schemas/auth.yaml#/components/schemas/User'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

  /users/me/plants:
    get:
      tags:
        - users
        - plants
      summary: Get user's plants
      description: Returns the list of all plants owned by the authenticated user
      operationId: getUserPlants
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          description: Filter by plant status
          schema:
            type: string
            enum: [active, inactive, maintenance]
      responses:
        '200':
          description: List of user's plants
          content:
            application/json:
              schema:
                type: object
                properties:
                  plants:
                    type: array
                    items:
                      $ref: './server/schemas/plant.yaml#/components/schemas/Plant'
                  total:
                    type: integer
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

  /plants:
    post:
      tags:
        - plants
      summary: Add a new plant
      description: Create a new plant configuration
      operationId: createPlant
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/plant.yaml#/components/schemas/PlantCreateRequest'
      responses:
        '201':
          description: Plant created successfully
          content:
            application/json:
              schema:
                $ref: './server/schemas/plant.yaml#/components/schemas/Plant'
        '400':
          $ref: './common/responses.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

  /plants/{plantId}:
    get:
      tags:
        - plants
      summary: Get plant details
      description: Returns detailed information about a specific plant
      operationId: getPlant
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/PlantId'
      responses:
        '200':
          description: Plant details
          content:
            application/json:
              schema:
                $ref: './server/schemas/plant.yaml#/components/schemas/PlantDetail'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

    put:
      tags:
        - plants
      summary: Update plant configuration
      description: Update the configuration of an existing plant
      operationId: updatePlant
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/PlantId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/plant.yaml#/components/schemas/PlantUpdateRequest'
      responses:
        '200':
          description: Plant updated successfully
          content:
            application/json:
              schema:
                $ref: './server/schemas/plant.yaml#/components/schemas/Plant'
        '400':
          $ref: './common/responses.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

    delete:
      tags:
        - plants
      summary: Delete a plant
      description: Remove a plant from the system
      operationId: deletePlant
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/PlantId'
      responses:
        '204':
          $ref: './common/responses.yaml#/components/responses/NoContent'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

  /plants/{plantId}/watering/trigger:
    post:
      tags:
        - plants
        - watering
      summary: Trigger watering for a plant
      description: Manually trigger the watering system for a specific plant
      operationId: triggerPlantWatering
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/PlantId'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: './server/schemas/measurement.yaml#/components/schemas/WateringTriggerRequest'
      responses:
        '200':
          description: Watering triggered
          content:
            application/json:
              schema:
                $ref: './server/schemas/measurement.yaml#/components/schemas/WateringTriggerResponse'
        '400':
          $ref: './common/responses.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

  /plants/{plantId}/measurements:
    get:
      tags:
        - plants
        - measurements
      summary: Get plant measurements history
      description: Returns historical sensor measurements for a plant
      operationId: getPlantMeasurements
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/PlantId'
        - $ref: './common/parameters.yaml#/components/parameters/StartDate'
        - $ref: './common/parameters.yaml#/components/parameters/EndDate'
        - $ref: './common/parameters.yaml#/components/parameters/SensorType'
        - $ref: './common/parameters.yaml#/components/parameters/Limit'
        - $ref: './common/parameters.yaml#/components/parameters/Offset'
      responses:
        '200':
          description: Measurements history
          content:
            application/json:
              schema:
                type: object
                properties:
                  measurements:
                    type: array
                    items:
                      $ref: './server/schemas/measurement.yaml#/components/schemas/Measurement'
                  total:
                    type: integer
                  pagination:
                    $ref: './common/schemas.yaml#/components/schemas/Pagination'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

    post:
      tags:
        - measurements
      summary: Add measurement data
      description: Store new sensor measurement data (typically called by controller)
      operationId: createMeasurement
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/PlantId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/measurement.yaml#/components/schemas/MeasurementCreateRequest'
      responses:
        '201':
          description: Measurement stored successfully
          content:
            application/json:
              schema:
                $ref: './server/schemas/measurement.yaml#/components/schemas/Measurement'
        '400':
          $ref: './common/responses.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

  /plants/{plantId}/watering/history:
    get:
      tags:
        - plants
        - watering
      summary: Get watering history
      description: Returns the watering history for a specific plant
      operationId: getWateringHistory
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/PlantId'
        - $ref: './common/parameters.yaml#/components/parameters/StartDate'
        - $ref: './common/parameters.yaml#/components/parameters/EndDate'
        - $ref: './common/parameters.yaml#/components/parameters/Limit'
        - $ref: './common/parameters.yaml#/components/parameters/Offset'
      responses:
        '200':
          description: Watering history
          content:
            application/json:
              schema:
                type: object
                properties:
                  history:
                    type: array
                    items:
                      $ref: './server/schemas/measurement.yaml#/components/schemas/WateringEvent'
                  total:
                    type: integer
                  pagination:
                    $ref: './common/schemas.yaml#/components/schemas/Pagination'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

  /plant-configs:
    get:
      tags:
        - plants
      summary: Get list of plant configuration templates
      description: Returns available plant configuration templates
      operationId: getPlantConfigs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of plant configuration templates
          content:
            application/json:
              schema:
                type: object
                properties:
                  configs:
                    type: array
                    items:
                      $ref: './server/schemas/plant.yaml#/components/schemas/PlantConfigTemplate'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

  /controllers:
    get:
      tags:
        - controllers
      summary: Get list of controllers
      description: Returns list of controllers owned by the user
      operationId: getControllers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of controllers
          content:
            application/json:
              schema:
                type: object
                properties:
                  controllers:
                    type: array
                    items:
                      $ref: './server/schemas/controller.yaml#/components/schemas/Controller'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'

    post:
      tags:
        - controllers
      summary: Register a new controller
      description: Register a new controller device to the user's account
      operationId: registerController
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/controller.yaml#/components/schemas/ControllerRegisterRequest'
      responses:
        '201':
          description: Controller registered successfully
          content:
            application/json:
              schema:
                $ref: './server/schemas/controller.yaml#/components/schemas/Controller'
        '400':
          $ref: './common/responses.yaml#/components/responses/BadRequest'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '409':
          $ref: './common/responses.yaml#/components/responses/Conflict'

  /controllers/{controllerId}:
    get:
      tags:
        - controllers
      summary: Get controller details
      description: Returns detailed information about a specific controller
      operationId: getController
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/ControllerId'
      responses:
        '200':
          description: Controller details
          content:
            application/json:
              schema:
                $ref: './server/schemas/controller.yaml#/components/schemas/ControllerDetail'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

    put:
      tags:
        - controllers
      summary: Update controller
      description: Update controller information
      operationId: updateController
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/ControllerId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/controller.yaml#/components/schemas/ControllerUpdateRequest'
      responses:
        '200':
          description: Controller updated
          content:
            application/json:
              schema:
                $ref: './server/schemas/controller.yaml#/components/schemas/Controller'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

    delete:
      tags:
        - controllers
      summary: Delete controller
      description: Remove a controller from the account
      operationId: deleteController
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/ControllerId'
      responses:
        '204':
          $ref: './common/responses.yaml#/components/responses/NoContent'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

  /controllers/{controllerId}/status:
    post:
      tags:
        - controllers
      summary: Update controller status
      description: Called by controller to update its status and sensor data
      operationId: updateControllerStatus
      security:
        - bearerAuth: []
      parameters:
        - $ref: './common/parameters.yaml#/components/parameters/ControllerId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './server/schemas/controller.yaml#/components/schemas/ControllerStatusUpdate'
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: './server/schemas/controller.yaml#/components/schemas/ControllerStatusResponse'
        '401':
          $ref: './common/responses.yaml#/components/responses/UnauthorizedError'
        '404':
          $ref: './common/responses.yaml#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      $ref: './common/security.yaml#/components/securitySchemes/bearerAuth'

