components:
  parameters:
    # Common Path Parameters
    PlantId:
      name: plantId
      in: path
      required: true
      description: Unique identifier of the plant
      schema:
        type: string
        format: uuid

    ControllerId:
      name: controllerId
      in: path
      required: true
      description: Unique identifier of the controller
      schema:
        type: string

    # Common Query Parameters
    StartDate:
      name: startDate
      in: query
      description: Start date for filtering (ISO 8601 format)
      schema:
        type: string
        format: date-time

    EndDate:
      name: endDate
      in: query
      description: End date for filtering (ISO 8601 format)
      schema:
        type: string
        format: date-time

    Limit:
      name: limit
      in: query
      description: Maximum number of records to return
      schema:
        type: integer
        minimum: 1
        maximum: 1000
        default: 100

    Offset:
      name: offset
      in: query
      description: Number of records to skip (for pagination)
      schema:
        type: integer
        minimum: 0
        default: 0

    SensorType:
      name: sensorType
      in: query
      description: Filter by sensor type
      schema:
        type: string
        enum: [temperature, humidity, luminosity]
